whereabouts.kubeconfig wrong in IPv6 only env
dougbtv/whereabouts pull request #47
Opened 2020-07-16 16:34 UTC by ohamada

Server address in whereabouts.kubeconfig file has wrong format when the kubernetes service has IPv6 address. The IPv6 server address must be wrapped in '[]' in the config file.

2020-09-10 14:20 UTC, crandles approved these changes

2020-10-25 08:42 UTC, xagent003 commented
Will this be merged soon?

2020-10-25 14:14 UTC, mithilarun requested changes

2020-10-25 14:14 UTC, mithilarun commented on script/install-cni.sh
> +
This isn't necessary. It is okay to wrap the service IP with square braces even if it isn't IPv6. See: https://github.com/projectcalico/cni-plugin/blob/be4df4db2e47aa7378b1bdf6933724bac1f348d0/k8s-install/scripts/install-cni.sh#L104-L153

2020-10-26 20:40 UTC, merged